items_to_analyse = ["Small Shield Extender II",
                    "Medium Shield Extender II",
                    "Large Shield Extender II",
                    "Medium Shield Booster II",
                    "Large Shield Booster II",
                    "Shield Boost Amplifier II",
                    "Small Remote Shield Booster II",
                    "Medium Remote Shield Booster II",
                    "Large Remote Shield Booster II",
                    "Data Analyzer II",
                    "Relic Analyzer II",
                    "Miner II",
                    "Armor Command Burst II",
                    "Information Command Burst II",
                    "Mining Foreman Burst II",
                    "Shield Command Burst II",
                    "Skirmish Command Burst II",
                    "Micro Auxiliary Power Core II",
                    "Large Cap Battery II",
                    "Cap Recharger II",
                    "Medium Energy Neutralizer II",
                    "Small Energy Neutralizer II",
                    "Reactor Control Unit II",
                    "Power Diagnostic System II",
                    "Medium Remote Armor Repairer II",
                    "Large Remote Armor Repairer II",
                    "720mm Howitzer Artillery II",
                    "280mm Howitzer Artillery II",
                    "200mm AutoCannon II",
                    "125mm Gatling AutoCannon II",
                    "Ballistic Control System II",
                    "Gyrostabilizer II",
                    "Heat Sink II",
                    "Magnetic Field Stabilizer II",
                    "Missile Guidance Computer II",
                    "Tracking Enhancer II",
                    "Sabre",
                    "Eris",
                    "Flycatcher",
                    "Bifrost",
                    "Scimitar",
                    "Damage Control II",
                    "Assault Damage Control II",
                    "Stasis Webifier II",
                    "Target Painter II",
                    "Warp Disruptor II",
                    "Warp Scrambler II",
                    "Drone Damage Amplifier II",
                    "Drone Link Augmentor II",
                    "Drone Navigation Computer II",
                    "Omnidirectional Tracking Enhancer II",
                    "Omnidirectional Tracking Link II",
                    "Covert Ops Cloaking Device II",
                    "Prototype Cloaking Device I",
                    "Improved Cloaking Device II",
                    "Sensor Booster II",
                    "Signal Amplifier II",
                    "Small Tractor Beam II",
                    "Medium Cargohold Optimization I",
                    "Medium Hyperspatial Velocity Optimizer I",
                    "Medium Low Friction Nozzle Joints I",
                    "Medium Auxiliary Thrusters II",
                    "Medium Cargohold Optimization II",
                    "Medium Hyperspatial Velocity Optimizer II",
                    "Medium Low Friction Nozzle Joints II",
                    "Medium Polycarbon Engine Housing II",
                    "Small Polycarbon Engine Housing II",
                    "Small Low Friction Nozzle Joints II",
                    "Small Hyperspatial Velocity Optimizer II",
                    "Small Low Friction Nozzle Joints I",
                    "Small Auxiliary Thrusters II",
                    "Small Hyperspatial Velocity Optimizer I",
                    "Small Cargohold Optimization I",
                    "Small Auxiliary Thrusters I",
                    "Medium Ionic Field Projector I",
                    "Small Ionic Field Projector II",
                    "Small Ionic Field Projector I",
                    "Medium Core Defense Field Extender I",
                    "Medium Core Defense Field Purger I",
                    "Medium Explosive Shield Reinforcer I",
                    "Medium EM Shield Reinforcer I",
                    "Medium Core Defense Field Extender II",
                    "Medium Core Defense Field Purger II",
                    "Medium EM Shield Reinforcer II",
                    "Medium Thermal Shield Reinforcer II",
                    "Small Core Defense Field Extender II",
                    "Small EM Shield Reinforcer II",
                    "Large Core Defense Field Extender I",
                    "Large EM Shield Reinforcer I",
                    "Medium Ice Harvester Accelerator I",
                    "Medium Mercoxit Mining Crystal Optimization I",
                    "Medium Salvage Tackle II",
                    "Small Salvage Tackle I",
                    "Small Gravity Capacitor Upgrade I",
                    "Small Memetic Algorithm Bank I",
                    "Small Signal Focusing Kit I",
                    "Small Memetic Algorithm Bank II",
                    "Signal Distortion Amplifier II",
                    "Interdiction Sphere Launcher I",
                    "Remote Sensor Dampener II",
                    "Signature Radius Suppressor I",
                    "Heavy Stasis Grappler II",
                    "Stasis Webifier II",
                    "Target Painter II",
                    "Warp Disruption Field Generator II",
                    "Auto Targeting System II",
                    "Co-Processor II",
                    "Passive Targeter II",
                    "Remote Sensor Booster II",
                    "Medium Cap Battery II",
                    "Small Cap Battery II",
                    "Heavy Capacitor Booster II",
                    "Medium Capacitor Booster II",
                    "Small Capacitor Booster II",
                    "Capacitor Flux Coil II",
                    "Capacitor Power Relay II",
                    "Heavy Energy Nosferatu II",
                    "Medium Energy Nosferatu II",
                    "Small Energy Nosferatu II",
                    "Small Remote Capacitor Transmitter II",
                    "Medium Remote Capacitor Transmitter II",
                    "Large Remote Capacitor Transmitter II",
                    "Gas Cloud Harvester II",
                    "Gas Cloud Scoop II",
                    "Ice Harvester II",
                    "Ice Mining Laser II",
                    "Modulated Deep Core Miner II",
                    "Mining Laser Upgrade II",
                    "Ice Harvester Upgrade II",
                    "Salvager II",
                    "Modulated Strip Miner II",
                    "Modulated Deep Core Strip Miner II",
                    "EM Armor Hardener II",
                    "Explosive Armor Hardener II",
                    "Kinetic Armor Hardener II",
                    "Thermal Armor Hardener II",
                    "1600mm Steel Plates II",
                    "200mm Steel Plates II",
                    "400mm Steel Plates II",
                    "800mm Steel Plates II",
                    "Large Armor Repairer II",
                    "Medium Armor Repairer II",
                    "Small Armor Repairer II",
                    "Explosive Coating II",
                    "Kinetic Coating II",
                    "EM Coating II",
                    "Thermal Coating II",
                    "EM Energized Membrane II",
                    "Explosive Energized Membrane II",
                    "Kinetic Energized Membrane II",
                    "Multispectrum Energized Membrane II",
                    "Thermal Energized Membrane II",
                    "Large Hull Repairer II",
                    "Medium Hull Repairer II",
                    "Small Hull Repairer II",
                    "Expanded Cargohold II",
                    "Nanofiber Internal Structure II",
                    "Reinforced Bulkheads II",
                    "Layered Energized Membrane II",
                    "Layered Coating II",
                    "Small Remote Armor Repairer II",
                    "1MN Afterburner II",
                    "10MN Afterburner II",
                    "100MN Afterburner II",
                    "Medium Micro Jump Drive",
                    "Large Micro Jump Drive",
                    "Micro Jump Field Generator",
                    "5MN Microwarpdrive II",
                    "50MN Microwarpdrive II",
                    "500MN Microwarpdrive II",
                    "Inertial Stabilizers II",
                    "Interdiction Nullifier II",
                    "Overdrive Injector System II",
                    "Warp Core Stabilizer II",
                    "Cargo Scanner II",
                    "Entosis Link I",
                    "Entosis Link II",
                    "Core Probe Launcher II",
                    "Expanded Probe Launcher II",
                    "Scan Acquisition Array II",
                    "Scan Pinpointing Array II",
                    "Scan Rangefinding Array II",
                    "Ship Scanner II",
                    "Survey Probe Launcher II",
                    "Survey Scanner II",
                    "X-Large Shield Booster II",
                    "Small Shield Booster II",
                    "Shield Flux Coil II",
                    "EM Shield Hardener II",
                    "Explosive Shield Hardener II",
                    "Kinetic Shield Hardener II",
                    "Multispectrum Shield Hardener II",
                    "Thermal Shield Hardener II",
                    "Shield Power Relay II",
                    "Shield Recharger II",
                    "Large EMP Smartbomb II",
                    "1400mm Howitzer Artillery II",
                    "800mm Repeating Cannon II",
                    "Entropic Radiation Sink II",
                    "Missile Guidance Enhancer II",
                    "Remote Tracking Computer II",
                    "Tracking Computer II",
                    ]
