items_to_analyse = ["Small Shield Extender II",
       "Medium Shield Extender II",
       "Large Shield Extender II",
       "Medium Shield Booster II",
       "Large Shield Booster II",
       "Shield Boost Amplifier II",
       "Small Remote Shield Booster II",
       "Medium Remote Shield Booster II",
       "Large Remote Shield Booster II",
       "Data Analyzer II",
       "Relic Analyzer II",
       "Miner II",
       "Armor Command Burst II",
       "Information Command Burst II",
       "Mining Foreman Burst II",
       "Shield Command Burst II",
       "Skirmish Command Burst II",
       "Micro Auxiliary Power Core II",
       "Large Cap Battery II",
       "Cap Recharger II",
       "Medium Energy Neutralizer II",
       "Small Energy Neutralizer II",
       "Reactor Control Unit II",
       "Power Diagnostic System II",
       "Medium Remote Armor Repairer II",
       "Large Remote Armor Repairer II",
       "720mm Howitzer Artillery II",
       "280mm Howitzer Artillery II",
       "200mm AutoCannon II",
       "125mm Gatling AutoCannon II",
       "Ballistic Control System II",
       "Gyrostabilizer II",
       "Heat Sink II",
       "Magnetic Field Stabilizer II",
       "Missile Guidance Computer II",
       "Tracking Enhancer II",
       "Sabre",
       "Eris",
       "Flycatcher",
       "Bifrost",
       "Scimitar",
       "Damage Control II",
       "Assault Damage Control II",
       "Stasis Webifier II",
       "Target Painter II",
       "Warp Disruptor II",
       "Warp Scrambler II",
       "Drone Damage Amplifier II",
       "Drone Link Augmentor II",
       "Drone Navigation Computer II",
       "Omnidirectional Tracking Enhancer II",
       "Omnidirectional Tracking Link II",
       "Covert Ops Cloaking Device II",
       "Prototype Cloaking Device I",
       "Improved Cloaking Device II",
       "Sensor Booster II",
       "Signal Amplifier II",
       "Small Tractor Beam II",
       "Medium Cargohold Optimization I",
       "Medium Hyperspatial Velocity Optimizer I",
       "Medium Low Friction Nozzle Joints I",
       "Medium Auxiliary Thrusters II",
       "Medium Cargohold Optimization II",
       "Medium Hyperspatial Velocity Optimizer II",
       "Medium Low Friction Nozzle Joints II",
       "Medium Polycarbon Engine Housing II",
       "Small Polycarbon Engine Housing II",
       "Small Low Friction Nozzle Joints II",
       "Small Hyperspatial Velocity Optimizer II",
       "Small Low Friction Nozzle Joints I",
       "Small Auxiliary Thrusters II",
       "Small Hyperspatial Velocity Optimizer I",
       "Small Cargohold Optimization I",
       "Small Auxiliary Thrusters I",
       "Medium Ionic Field Projector I",
       "Small Ionic Field Projector II",
       "Small Ionic Field Projector I",
       "Medium Core Defense Field Extender I",
       "Medium Core Defense Field Purger I",
       "Medium Explosive Shield Reinforcer I",
       "Medium EM Shield Reinforcer I",
       "Medium Core Defense Field Extender II",
       "Medium Core Defense Field Purger II",
       "Medium EM Shield Reinforcer II",
       "Medium Thermal Shield Reinforcer II",
       "Small Core Defense Field Extender II",
       "Small EM Shield Reinforcer II",
       "Large Core Defense Field Extender I",
       "Large EM Shield Reinforcer I",
       "Medium Ice Harvester Accelerator I",
       "Medium Mercoxit Mining Crystal Optimization I",
       "Medium Salvage Tackle II",
       "Small Salvage Tackle I",
       "Small Gravity Capacitor Upgrade I",
       "Small Memetic Algorithm Bank I",
       "Small Signal Focusing Kit I",
       "Small Memetic Algorithm Bank II"]